name: Build & Push to ACR

on:
  push:
    branches: [ "main" ]

env:
  ACR_LOGIN_SERVER: ${{ vars.ACR_LOGIN_SERVER }}   # Variables(변수) 사용

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: ACR docker login (admin creds)
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build image
        run: |
          IMAGE=${{ env.ACR_LOGIN_SERVER }}/backendweb
          docker build -t $IMAGE:latest -t $IMAGE:${{ github.sha }} .

      - name: Push image
        run: |
          IMAGE=${{ env.ACR_LOGIN_SERVER }}/backendweb
          docker push $IMAGE:latest
          docker push $IMAGE:${{ github.sha }}
