name: Build & Push to ACR
on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      ACR_LOGIN_SERVER: jamong1014.azurecr.io
      IMAGE_NAME: backendweb
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
      ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}

    steps:
      - uses: actions/checkout@v4

      - name: Azure login
        if: ${{ env.AZURE_CREDENTIALS != '' }}
        uses: azure/login@v1
        with:
          creds: ${{ env.AZURE_CREDENTIALS }}

      - name: ACR docker login (admin creds)
        if: ${{ env.ACR_USERNAME != '' && env.ACR_PASSWORD != '' }}
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.ACR_LOGIN_SERVER }}
          username: ${{ env.ACR_USERNAME }}
          password: ${{ env.ACR_PASSWORD }}

      - name: Build image
        run: |
          IMAGE=${{ env.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}
          docker build -t $IMAGE:latest -t $IMAGE:${{ github.sha }} .

      - name: Push image
        run: |
          IMAGE=${{ env.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}
          docker push $IMAGE:latest
          docker push $IMAGE:${{ github.sha }}
